[build]
  command = "git clone https://github.com/mnjm/kayal.git exampleSite --depth 1 --single-branch --branch exampleSite && hugo --gc --minify -D --source ./exampleSite --destination ../public --baseURL $URL"
  publish = "public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.125.7"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.125.7"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.125.7"
