# Site settings

title: Ninad Khargonkar

email: nkhargonkar@cs.umass.edu

description: > # this means to ignore newlines until "baseurl:"
	" When in doubt, use brute force." --Ken Thompson

url: "https://ninception.github.io" # the base hostname & protocol for your site
m

github_username:  ninception


