#+TITLE: Welcome to my homepage!
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/worg.css" />

[[./index.html][home]] | [[./notes.html][notes]] | [[./misc.html][misc]]

* About me

Ninad Khargonkar \\
College of Information and Computer Sciences \\
University of Massachusetts Amherst \\
Email: nkhargonkar [at] cs [dot] umass [dot] edu

I am a final year masters student in computer science at the 
[[https://www.umass.edu/][University of Massachusetts Amherst]].
I completed my undergraduate education from
[[https://www.iitk.ac.in/][IIT Kanpur]] in 2017  with a bachelors degree from the department of 
mathematics and statistics. Hopefully I will be able to use my education
for a good cause!

I like to read about all topics under the sun. 
When I am not into some reading or sleeping, I like to play football 
and occasionally going for running and bicycling. I am trying to pick up 
sketching from the awesome resource of [[https://drawabox.com/][drawabox]] along with developing a 
taste for all genres of music (learning to play a basic instrument helps
a lot in this regard).

Here are few links for more "professional" information:
- [[https://www.linkedin.com/in/ninadkhargonkar/][linkedin]]
- [[https://github.com/ninception][github]]

