#!/bin/bash

Rootdir="."
AUTHOR="Ninad"
CSS="${Rootdir}/css/pandoc.css"

for mf in $Rootdir/*.md
do
	filename="${mf%.*}"
	echo "Converting $mf to $filename.html" #Pandoc command for conversion to html:		
	pandoc \
        -c "$CSS" \
		-V author-meta="$AUTHOR" \
		-f markdown -t html5 $mf -o $filename.html		
done

# Can even use a custom template with:
# --template default_mod.html 
# -s stands for standalone
# --css mycssfile.css (css linking already done in HEADER )
# pandoc -c ./pandoc.css --to=html5 index.md -o index.html
