#!/bin/bash

AUTHOR="Ninad"
HEADER="./_includes/head.html"
BEFORE="./_includes/before-body.html"
AFTER="./_includes/after-body.html"

for mf in ./*.md
do
	filename="${mf%.*}"
	echo "Converting $mf to $filename.html" #Pandoc command for conversion to html:		
	pandoc \
		-H "$HEADER" \
		-B "$BEFORE" \
		-A "$AFTER" \
		-V author-meta="$AUTHOR" \
		-s -f markdown -t html5 $mf -o $filename.html		
done

# Can even use a custom template with:
# --template default_mod.html 
# -s stands for standalone
# --css template.css (css linking already done in HEADER 
